# Generated by Django 3.2.7 on 2021-11-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFoods',
            fields=[
                ('savedFoodsId', models.AutoField(primary_key=True, serialize=False)),
                ('recipes', models.ManyToManyField(blank=True, to='RestAPI.Recipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.user'),
        ),
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('foodListId', models.AutoField(primary_key=True, serialize=False)),
                ('recipes', models.ManyToManyField(blank=True, to='RestAPI.Recipe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.user')),
            ],
        ),
    ]
