# Generated by Django 3.2.8 on 2021-11-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='New Recipe', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.user'),
        ),
        migrations.AlterField(
            model_name='savedfoods',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
