# Generated by Django 3.2.7 on 2021-11-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_alter_recipe_image'),
        ('RestAPI', '0002_auto_20211101_1343'),
    ]

    operations = [
    ]
