# Generated by Django 3.2.7 on 2021-11-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_merge_0002_alter_recipe_image_0002_auto_20211101_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
